server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/regist_web?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/mybatis/mappers/*Mapper.xml
  type-aliases-package: com.entities

#邮件配置(发件人）
email:
  host: smtp.163.com
  username: 15989746839@163.com
  password: 15989746839wsp
  senderName: 15989746839@163.com