spring:
  datasource:
    url: jdbc:mysql://localhost:3333/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
  mvc:  ## jsp ##
    view:
      prefix: /pages/
      suffix: .jsp

mybatis:
  mapper-locations: classpath*:/mybatis/mappers/*Mapper.xml #包扫描 mapper.xml 类
  type-aliases-package: com.webcode.springboot.entities  # 指定相应 mapper.xml 中实体 javabean 的所在位置
server:
  port: 8081
