server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/sb_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath*:/mybatis/mappers/*Mapper.xml
#  type-aliases-package: com.webcode.springboot.entities
